# the speed to set the train at if the neutral button is clicked.
neutral-speed: 0.4

# action bar is the text right above your inventory that displays the current speed of the train
action-bar-enabled: true

# the max speed a train is allowed to go at
max-speed: 3.0

# using the "launch" lever launches to neutral-speed, but how many blocks should it take to react this speed?
block-distance: 15