name: TControls
version: 1.0-SNAPSHOT
main: me.delected.tcontrols.TControls
api-version: 1.16
depend: [ Train_Carts ]
authors: [ Delected_ ]
description: A control panel for your TrainCarts train right from your inventory!
website: https://delected.me/

commands:
  tcontrols:
    description: toggles the driver mode
    usage: /<command>
    aliases: ['tcon', 'tcons']
  tcontrolsreload:
    description: reloads the config.yml file
    usage: /<command>
    aliases: ['tconreload', 'tcr', 'tcontrolreload']
  tcontrolsdebug:
    description: sends a debug message (used for support)
    usage: /<command>
    aliases: ['tcdebug', 'tcd', 'tcontroldebug']